### ISSUE TITLE
Supporting Regex on match()?

### ISSUE THREAD

**Issue by yusef-ho** [Yoctol/bottender-compose#88]
Hello,
Is match() supporting Regex on answer??
Will this is supporting in the future?

Thanks

**Comment by chentsulin** [comment]
In the short term, I'd say no.
`match` providers value matching which just like what `switch case` does.

If you want to check input text using regex, you can use `condition` instead:

```js
condition([
  [isTextMatch(/abc/), sendText('a')],
  [isTextMatch(/def/), sendText('b')],
  [alwaysTrue(), sendText('c')],
]);
```
